---
stages:
    - build

docker build:
    image: docker:stable
    services:
        - name: docker:dind
    variables:
      VERSION: 'stable'
    stage: build
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --pull --force-rm -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE:$VERSION
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
        - docker push $CI_REGISTRY_IMAGE:latest
    only:
        - master
